# Generated by Django 5.2.8 on 2025-12-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo4j_id', models.CharField(db_index=True, help_text='Corresponding Neo4j node ID', max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Last sync with Neo4j')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Thought',
                'verbose_name_plural': 'Thoughts',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['neo4j_id'], name='thoughts_ap_neo4j_i_b093f8_idx'), models.Index(fields=['is_active'], name='thoughts_ap_is_acti_17706e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo4j_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('en_title', models.CharField(blank=True, max_length=255)),
                ('en_content', models.TextField(blank=True)),
                ('es_title', models.CharField(blank=True, max_length=255)),
                ('es_content', models.TextField(blank=True)),
                ('fr_title', models.CharField(blank=True, max_length=255)),
                ('fr_content', models.TextField(blank=True)),
                ('hi_title', models.CharField(blank=True, max_length=255)),
                ('hi_content', models.TextField(blank=True)),
                ('zh_title', models.CharField(blank=True, max_length=255)),
                ('zh_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='thoughts_app.thought')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'indexes': [models.Index(fields=['neo4j_id'], name='thoughts_ap_neo4j_i_015a14_idx')],
            },
        ),
    ]
