# Generated by Django 5.2.8 on 2025-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='parent_id',
            field=models.CharField(blank=True, help_text='ID of the parent topic/thought', max_length=255, null=True),
        ),
    ]
