# Generated by Django 5.2.8 on 2025-12-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts_app", "0002_thought_parent_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThoughtTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thought",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thought_tags",
                        to="thoughts_app.thought",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tag"], name="thoughts_ap_tag_0647c0_idx")
                ],
                "unique_together": {("thought", "tag")},
            },
        ),
    ]
