# Generated by Django 5.2.8 on 2025-12-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts_app', '0003_thoughttag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Thought Content', 'verbose_name_plural': 'Thought Contents'},
        ),
        migrations.AddField(
            model_name='thought',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
