# Generated by Django 5.2.8 on 2025-12-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('single', 'Single Topic Sync')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo4j_id', models.CharField(db_index=True, help_text='Corresponding Neo4j node ID', max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField(db_index=True, default=0)),
                ('parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Last sync with Neo4j')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['level', 'title'],
                'indexes': [models.Index(fields=['level', 'title'], name='topics_app__level_31056e_idx'), models.Index(fields=['neo4j_id'], name='topics_app__neo4j_i_fba9f8_idx'), models.Index(fields=['is_active', 'level'], name='topics_app__is_acti_0355f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_tags', to='topics_app.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['tag'], name='topics_app__tag_cb604f_idx')],
                'unique_together': {('topic', 'tag')},
            },
        ),
    ]
