# Generated by Django 5.2.8 on 2025-12-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_app', '0002_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='en_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='description',
            name='en_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='description',
            name='es_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='description',
            name='es_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='description',
            name='fr_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='description',
            name='fr_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='description',
            name='hi_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='description',
            name='hi_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='description',
            name='zh_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='description',
            name='zh_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='description',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
