# Generated by Django 5.2.8 on 2025-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name or Title of the source node', max_length=255)),
                ('source_type', models.CharField(choices=[('Topic', 'Topic'), ('Thought', 'Thought'), ('Quote', 'Quote'), ('Passage', 'Passage')], db_index=True, max_length=50)),
                ('source_id', models.CharField(db_index=True, help_text='ID of the source node (e.g., Neo4j ID or PK)', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags associated with the source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag Source',
                'verbose_name_plural': 'Tag Sources',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='tags_app_ta_source__3a0090_idx'), models.Index(fields=['name'], name='tags_app_ta_name_a2a44c_idx')],
                'unique_together': {('source_type', 'source_id')},
            },
        ),
    ]
