# Generated by Django 5.2.8 on 2025-12-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo4j_id', models.CharField(db_index=True, help_text='Corresponding Neo4j node ID', max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('book', models.CharField(blank=True, max_length=255)),
                ('chapter', models.CharField(blank=True, max_length=255)),
                ('verse', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Last sync with Neo4j')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Passage',
                'verbose_name_plural': 'Passages',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['neo4j_id'], name='passages_ap_neo4j_i_36fdcb_idx'), models.Index(fields=['is_active'], name='passages_ap_is_acti_1cd006_idx')],
            },
        ),
        migrations.CreateModel(
            name='PassageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo4j_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('en_title', models.CharField(blank=True, max_length=255)),
                ('en_content', models.TextField(blank=True)),
                ('es_title', models.CharField(blank=True, max_length=255)),
                ('es_content', models.TextField(blank=True)),
                ('fr_title', models.CharField(blank=True, max_length=255)),
                ('fr_content', models.TextField(blank=True)),
                ('hi_title', models.CharField(blank=True, max_length=255)),
                ('hi_content', models.TextField(blank=True)),
                ('zh_title', models.CharField(blank=True, max_length=255)),
                ('zh_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='passages_app.passage')),
            ],
            options={
                'verbose_name': 'Passage Content',
                'verbose_name_plural': 'Passage Contents',
                'indexes': [models.Index(fields=['neo4j_id'], name='passages_ap_neo4j_i_85a212_idx')],
            },
        ),
    ]
