# Generated by Django 5.2.8 on 2025-12-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='source',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='PassageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_tags', to='passages_app.passage')),
            ],
            options={
                'indexes': [models.Index(fields=['tag'], name='passages_ap_tag_7b0e54_idx')],
                'unique_together': {('passage', 'tag')},
            },
        ),
    ]
