# Generated by Django 5.2.8 on 2025-12-10 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passages_app", "0002_passage_source_passagetag"),
        ("topics_app", "0003_description_en_content_description_en_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passage",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="passage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passages",
                to="topics_app.topic",
            ),
        ),
    ]
