# Generated by Django 5.2.8 on 2025-12-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartHerePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to the Book of Wisdom!', max_length=255)),
                ('subtitle', models.CharField(blank=True, default="Formerly 'The Book of Tweets: Proverbs for the Modern Age'", max_length=255)),
                ('hero_image_url', models.CharField(default='/assets/images/hero_image.jpg', help_text='Path to the hero image', max_length=255)),
                ('content', models.TextField(help_text='Main content of the page. Supports HTML.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Start Here Page Content',
                'verbose_name_plural': 'Start Here Page Content',
            },
        ),
    ]
