# Generated by Django 5.2.8 on 2025-12-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='book_link',
            field=models.CharField(blank=True, help_text='URL to the book', max_length=500),
        ),
    ]
