# Generated by Django 5.2.8 on 2025-12-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_quote_book_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_tags', to='quotes_app.quote')),
            ],
            options={
                'indexes': [models.Index(fields=['tag'], name='quotes_app__tag_b6df85_idx')],
                'unique_together': {('quote', 'tag')},
            },
        ),
    ]
