# Generated by Django 5.2.8 on 2025-12-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_quotetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='level',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
