# Generated by Django 5.2.8 on 2025-12-10 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0004_quote_level'),
        ('topics_app', '0003_description_en_content_description_en_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='topics_app.topic'),
        ),
    ]
